In [3]:
import math

def basic_sigmoid(x):
    s = 1 / (1 + math.exp(-x))
    return s

basic_sigmoid(4)

0.9820137900379085

In [5]:
x = [1, 2, 3]
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [7]:
import numpy as np

x = np.array([1, 2, 3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [13]:
x = np.array([1, 2, 3])
print(x+3)

[4 5 6]


In [15]:
np.exp?

Call signature:  np.exp(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'exp'>
File:            c:\users\admin\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the exponential of all elements in the input array.

Parameters
----------
x : array_like
    Input values.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
 

In [27]:
def sigmoid(x):
    s = 1 / (1 + np.exp(-x))
    return s

In [29]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

## Sigmoid Gradient

In [47]:
def sig_grad(x):
    s = 1 / (1 + np.exp(-x))
    result =  s*(1 - s)
    return result

In [49]:
x = 5
sig_grad(x)

0.006648056670790033

## Reshaping vectors

In [62]:
def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2], 1)
                      
    return v

In [64]:
image = np.array([[[0.678, 0.293],
                  [0.907, 0.528], 
                   [0.421, 0.4501]],
                 [[0.928, 9.966],
                 [0.856, 0.524],
                 [0.199, 0.274]],
                 [[0.689, 0.005],
                 [0.108, 0.499],
                 [0.567, 0.876]]])

print("image2vector(image) = \n" + str(image2vector(image)))

image2vector(image) = 
[[6.780e-01]
 [2.930e-01]
 [9.070e-01]
 [5.280e-01]
 [4.210e-01]
 [4.501e-01]
 [9.280e-01]
 [9.966e+00]
 [8.560e-01]
 [5.240e-01]
 [1.990e-01]
 [2.740e-01]
 [6.890e-01]
 [5.000e-03]
 [1.080e-01]
 [4.990e-01]
 [5.670e-01]
 [8.760e-01]]


## Normalizing rows

In [85]:
def normalize_rows(x):
    x_norm = np.linalg.norm(x,axis = 1, keepdims = True)
    x = x / x_norm
    return x

In [87]:
x = np.array([
    [0,1000,4],
    [2, 6, 4]])

normalize_rows(x)

array([[0.        , 0.999992  , 0.00399997],
       [0.26726124, 0.80178373, 0.53452248]])

## Softmax Function

In [90]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum
    return s

In [92]:
x = np.array([
    [9,2,5,0,0],
    [1, 2, 3, 4, 5]
])

softmax(x)

array([[9.80897665e-01, 8.94462891e-04, 1.79657674e-02, 1.21052389e-04,
        1.21052389e-04],
       [1.16562310e-02, 3.16849208e-02, 8.61285444e-02, 2.34121657e-01,
        6.36408647e-01]])

## Vectorization

In [101]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5]
x2 = [9, 2, 2, 9, 0 ,9, 2]

tic = time.process_time()
dot = 0;

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print("dot = " + str(dot) + "\n --- Cumputation time = " + str(1000*(toc - tic)) + "ms")

dot = 168
 --- Cumputation time = 0.0ms
